name: MyAssumptionApp
options:
  bundleIdPrefix: com.assumption
settings:
  GENERATE_INFOPLIST_FILE: YES
targets:
  MyAssumptionApp:
    type: application
    platform: iOS
    deploymentTarget: "17.4"
    sources: MyAssumptionApp
    scheme:
      testTargets:
        - MyAssumptionAppTests
    settings:
      base:
        DEVELOPMENT_TEAM: RHBH6Q62PG
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
    postCompileScripts:
      - script: /opt/homebrew/bin/swiftlint lint --quiet
        name: Swiftlint
  MyAssumptionAppTests:
    type: bundle.unit-test
    platform: iOS
    sources: MyAssumptionAppTests
    dependencies:
      - target: MyAssumptionApp
    settings:
      base:
        DEVELOPMENT_TEAM: RHBH6Q62PG